### ISSUE TITLE
Drawer

### ISSUE THREAD

**Issue by matheusps** [vtex/shoreline#1537]
## Drawer

[![Figma](https://img.shields.io/badge/figma-%23F24E1E.svg?style=for-the-badge&logo=figma&logoColor=white)](https://www.figma.com/file/bsfo0Ad4nqoWWSUSELEJHv/Drawer?type=design&node-id=17%3A65221&mode=design&t=TjSmc8MwTo3oeY2L-1) [![CodeSandbox](https://img.shields.io/badge/Codesandbox-040404?style=for-the-badge&logo=codesandbox&logoColor=DBDBDB)](https://codesandbox.io/p/sandbox/drawer-wgnfh3?file=%2Fsrc%2Fdrawer%2Fdrawer.css)

### Context

A Drawer (or Sheet) is a type of Dialog that is docked to a part of the screen, normally on: right, left, or bottom. Remember that like any other Dialog, a Drawer can be `modal` or `non-modal`. While exploring, I came across different types of drawers: https://component.gallery/components/drawer/. Putting it on the side of our current DS, I concluded that:

1. The Drawer, in the context of Shoreline, enables users to preview and interact with information in multiple contexts. The user should always be able to interact with the background. This means that the Drawer is a **NON-Modal Dialog**.
2. If we create a Modal-Drawer it will confuse the design system users wether they should use a Modal or a Drawer. So, let's not do this for now.
3. Multiple sizes are necessary, so we have three: `small`, `medium`, `large`.
4. While on desktop, the drawer opens on the right (left on rtl).
5. While on mobile, the drawer opens on the bottom - acting as a bottom sheet.  

### API

Composable (full) form:

```jsx
<DrawerProvider>
  <DrawerTrigger>{/* ... */}</DrawerTrigger>
  <DrawerPopover>
    <DrawerHeader>
      <DrawerHeading>{/* ... */}</DrawerHeading>
    </DrawerHeader>
    <DrawerContent>{/* ... */}</DrawerContent>
  </DrawerPopover>
</DrawerProvider>
```

The reduced form would be:

```jsx
<Drawer label="Label of the button">
  <DrawerHeader>
    <DrawerHeading>{/* ... */}</DrawerHeading>
  </DrawerHeader>
  <DrawerContent>{/* ... */}</DrawerContent>
<Drawer>
```

##### Size

- type: `'small' | 'medium' | 'large'`
- description: The size of the modal

##### Direction

- type: `'bottom' | 'right' | 'left'`
- description: The part of the screen where the Drawer is docked

### References 

- [Modal and NonModal Dialogs, NNGroup](https://www.nngroup.com/articles/modal-nonmodal-dialog/)
- [Bottom Sheet, NNGroup](https://www.nngroup.com/articles/bottom-sheet/)
- [Emilkowalski's Vaul](https://github.com/emilkowalski/vaul)
- [Shadcn-UI Drawer](https://ui.shadcn.com/docs/components/drawer)
- [Radix UI Dialog](https://www.radix-ui.com/primitives/docs/components/dialog)
- [Shoreline State Management](https://shoreline.vtex.com/guides/state-management)

**Comment by malu-viana** [comment]
All scenarios I've used the drawer was as a non-modal dialog and also in the medium size. Usually when I need to use a dialog that blocks the user to interact with the UI I choose to use the modal component. 

So I agree that two sizes contemplates our scenarios on desktop, but don't you think that when it comes to mobile the larger size, almost full page, would be usefull since mobile doesn't have the same distinction between modal and drawer (the point of blocking interaction) as it does on desktop?

**Comment by elleenvs-d** [comment]
> I only missed a footer for the actions, which is common to all our scenarios, and the title having the behavior of remaining on the screen in drawer content with scroll.

In Security Products, we had the opposite. For Security Monitor, It was necessary to have the main actions at the top. [Here](https://www.figma.com/design/BsyDtb39GNX744bWMvnZ7Z/Security-Monitor?node-id=2423-30735&t=k7CEtLG5jr22ck0e-1.) are some explorations

**Comment by beatrizmilhomem** [comment]
> In Security Products, we had the opposite. For Security Monitor, It was necessary to have the main actions at the top. [Here](https://www.figma.com/design/BsyDtb39GNX744bWMvnZ7Z/Security-Monitor?node-id=2423-30735&t=k7CEtLG5jr22ck0e-1.) are some explorations

@elleenvs-d The [current proposal ](https://www.figma.com/design/bsfo0Ad4nqoWWSUSELEJHv/Drawer?node-id=175-99361&t=o1e8lo9Mzskf8p24-4) already includes the possibility to add Buttons to the Header. Did you test that?

> So I agree that two sizes contemplates our scenarios on desktop, but don't you think that when it comes to mobile the larger size, almost full page, would be usefull since mobile doesn't have the same distinction between modal and drawer (the point of blocking interaction) as it does on desktop?

@malu-viana That is a good point. Maybe we could have only one variant for mobile and the size would be adjusted according to the needs when applying it to an interface. @felipepowlist just brought up a scenario in which it made sense to occupy the full height since the content was extensive, for example. What do you all think about that? @davicostalf @matheusps

**Comment by davicostalf** [comment]
@matheusps Is your implementation already considering mobile? Or should we leave mobile aside for the moment?

@felipepowlist By looking at your explorations, I believe the proposed the design would already fit your needs. Since the inclusion of a header/footer is optional, and your scenario is non-modal. The only open question for me is this stack of drawers, if it would be possible to achieve something like this by using the implementation matheus is proposing. @matheusps [what do you think?](https://www.figma.com/design/uVFkApBTiuckbOoMiTQY8j/%F0%9F%93%90-Form-handoff---1.0?node-id=240-26581&t=JGDaJzrYuuDJDzIT-4)

From the scenarios you've all shared in this thread I believe we can move ahead with the proposal that Bia shared, since is seems to cover well all the use cases. The `small` size would suffice for details, the `medium` size would be ideal for more extensive information or simpler forms and the `large` size would be best for more complex forms.

**Comment by matheusps** [comment]
@davicostalf 

1. Yes, it considers mobile. But we can leave aside if needed.
2. It is possible to nest drawers. But, I would be carefully with the number of drawers we nest. 

I agree if the 3 sizes.

**Comment by beatrizmilhomem** [comment]
* Component added to the [Figma library](https://www.figma.com/design/PWGSQ26U55u8E34JWn9ZYE/Shoreline-%E2%80%93-Components?node-id=5744-31605&t=mMAHDdjCKsTkqQwQ-4), including the small and medium size for desktop.
* [Component specs](https://www.figma.com/design/NmC9IaAfxgh4amOtYJMiWw/Drawer-Handoff?node-id=0-1&t=mUmgVxG9y0rLtQDU-1).

**Comment by beatrizmilhomem** [comment]
Issue is ready to be moved to the implementation Backlog.

---

### Summary
Implement the Drawer component according to the [component specs](https://www.figma.com/design/NmC9IaAfxgh4amOtYJMiWw/Drawer-Handoff?node-id=0-1&t=mUmgVxG9y0rLtQDU-1).

**Comment by beatrizmilhomem** [comment]
https://github.com/vtex/shoreline/issues/1782
