### ISSUE TITLE
Style overwriting when using the admin-ui and shoreline in the same app

### ISSUE THREAD

**Issue by myllenaalves** [vtex/shoreline#1710]
### Problem

The components from @vtex/shoreline have incorrect styling when used in an app with admin-ui.

### Expected behavior

The behavior of the component according to the guide: https://shoreline.vtex.com/components.

### Reproducible Example

https://codesandbox.io/p/sandbox/shoreline-test-myllena-yfsvkx?file=%2Fsrc%2FApp.tsx%3A17%2C1

### Suggested solution

It's caused by the <ThemeProvider>.

_No response_

### Additional context

https://vtex.slack.com/archives/C01DVTFA4VA/p1720549817337259

### Package

@vtex/shoreline

### Packages version

    "@vtex/admin-ui": "^0.136.1",
    "@vtex/shoreline": "^1.1.1",

### Package Manager

pnpm

**Comment by matheusps** [comment]
This happens due to [Shoreline's cascade layers](https://shoreline.vtex.com/guides/styling/cascade-layers). You have two solutions here: 

1. Use admin-ui theme-provider on specific parts instead of the root for your applications. Also, disable global styles with the `experimentalDisableGlobalStyles` prop. https://admin-ui.vercel.app/documentation/developing/theming#global. I would try this option first, since you keep all the advantages of layers on the Shoreline parts.
2. Use the unlayered version of Shoreline. This can be achieved by importing `@vtex/shoreline/css/unlayered` instead of `@vtex/shoreline/css`. [Your same codesandbox link with this option](https://codesandbox.io/p/sandbox/shoreline-test-myllena-yfsvkx?file=%2Fsrc%2FApp.tsx%3A17%2C1). This works well, but be aware that not using layers may create inconsistencies in CSS overrides. I would recommend returning to the layered versions after you upgrade from admin-ui to shoreline.

**Comment by beatrizmilhomem** [comment]
Hello @myllenaalves ! Did you manage to solve your problem?

**Comment by myllenaalves** [comment]
> Hello @myllenaalves ! Did you manage to solve your problem?

Hi! Yes. We choose to follow Matheus' second suggestion. Thank you.
