### ISSUE TITLE
Select: gap between input and popover should continue the same after removing the Label in the Figma component

### ISSUE THREAD

**Issue by beatrizmilhomem** [vtex/shoreline#1763]
### Problem

Original issue: https://github.com/vtex/shoreline/issues/1744

When we remove the label from the Select Figma component, the popover stays in the same place, causing the gap between the input and the popover to become large.
![image](https://github.com/user-attachments/assets/65871061-c34e-40ee-b063-cb7b730280cc)

### Expected behavior

The gap should continue the same.

![image](https://github.com/user-attachments/assets/41a95fe2-81c8-4f81-be7a-f9c471239fc8)

### Package Manager

pnpm

**Comment by felipepowlist** [comment]
Hi @beatrizmilhomem. I fixed this issue in this branch. I also fixed the interaction of the checkbox. It was "on click" instead of "while hovering". Please check and see if it's ok

https://www.figma.com/design/PWGSQ26U55u8E34JWn9ZYE/branch/rDCbPI89OmxKSegJETLrGY/Shoreline-%E2%80%93-Components?m=auto&t=FHr0wACi2JBQfUuT-1

**Comment by davicostalf** [comment]
Hi @felipepowlist! Thanks for the fix. I've noticed in the branch that while the Select Popover now works when there's not a label, it no longer works when there's a help text or error text. This can add additional friction when swapping instances, since a previously-existing help text or error text would need to be hidden, and vice-versa.

I think the most complete solution for this issue would be moving the popover to be inside the Input and removing it's clip content property. The downside is that the focus ring would also need to be solved with an overlay, like it is on the focus state of the date picker.

What do you think?

**Comment by felipepowlist** [comment]
I tried this approach but when we remove the clip content we lose the focus ring. My idea was to put the input + popover inside a container. I think it works now. 

<img width="1320" alt="Captura de Tela 2024-07-26 às 11 09 19" src="https://github.com/user-attachments/assets/097d77ce-0447-454b-88f6-0bde2f54568c">

**Comment by beatrizmilhomem** [comment]
@felipepowlist yes, you can name the layer as Input + Popover. It is working perfectly!
I just noticed the `label.` text property is missing in some variants (it was missing in the original component). Since you're fixing the component, can you fix that too, please?

When you're done, please let us know, so we can make the final review and move on with merging. :)

**Comment by felipepowlist** [comment]
I think it's fixed now @beatrizmilhomem :)

**Comment by davicostalf** [comment]
Great! We should apply this change in the Date Picker components as well, since they also have a popover that needs to accompany a field.

**Comment by beatrizmilhomem** [comment]
Perfect, @felipepowlist ! I will merge your branch. :)

@davicostalf I will create a different issue for that.
